### ISSUE TITLE
Crash in shrinker_compress.

### ISSUE THREAD

**Issue by xcrh** [inikep/lzbench#12]
After messing with various files I've eventually stumbled on another edge case.

Configuration:
GCC 5.2 @ x86-64, Linux.
lzbench -dev branch at 949291ca3810f98bf674901806020cefc0d99994
Default flags, etc. 

Info:
 Shrinker compressor could crash during compression if you'll try to compress some >=2Mb poorly compressible file (I've tested it on ~2Mb ogg sound).
 This only happens with -O3, so it have to be demoted to -O2 as well, unfortunately.

Backtrace follows (partially optimized out due to -O3)
```
Program received signal SIGSEGV, Segmentation fault.
shrinker_compress (in=in@entry=0x7ffff7e20010, out=out@entry=0x7ffff7bf9010, size=size@entry=1920106) at shrinker/shrinker.c:138
138	    MEMCPY_NOOVERLAP_NOSURPASS(dst, p_last_lit, src);
(gdb) bt full
#0  shrinker_compress (in=in@entry=0x7ffff7e20010, out=out@entry=0x7ffff7bf9010, size=size@entry=1920106) at shrinker/shrinker.c:138
        ht = {1919054, 3357316263, 4162657658, 1209854581, 672971416, 3894190478, 2820466262, 3491576845, 2820444135, 941383503, 
          807186245, 1826989, 2954671924, 1746742483, 3625762943, 1917658, 4162616814, 1918002, 2686268610, 1896331, 941335832, 
          2015127924, 4162626043, 1344092269, 3088835399, 807225254, 538773969, 672976133, 2820490928, 1478289263, 941385833, 3759992215, 
          1209868260, 1746709675, 4028425939, 404506619, 3223140401, 2954639374, 941392504, 1746747208, 3088871349, 3894225328, 
          2954700106, 2552038736, 2552022291, 270300864, 807216336, 270345901, 2149292566, 3088922298, 3759994886, 270301143, 1746712067, 
          3223120066, 2552025977, 2283587384, 136127415, 807173287, 404554225, 2417837136, 2820459038, 2686235255, 1075633669, 4162633020, 
          2954616933, 404536190, 2820473731, 3357266512, 1880965274, 3760003906, 3894220498, 672974319, 672983291, 538742501, 672970612, 
          2686252339, 1902348, 1746721687, 1880962511, 1344014576, 2552037343, 4162647782, 2686253481, 3894148377, 2954677885, 1746740461, 
          4028403285, 807205936, 2551983821, 941433739, 2820375539, 941408963, 1880953599, 1858117, 2283562976, 2417829796, 3894180036, 
          4162618722, 1209875690, 136124613, 807210168, 2417812184, 1880879366, 1343971640, 3088926190, 3491510128, 2552049476, 
          1209727692, 3088896462, 807201356, 270336482, 4028445869, 4028423729, 1746655281, 1902781, 270320085, 2552026574, 1209850856, 
          1075655571, 3088898532, 2015178583, 538756589, 672998424, 941437137, 2954673159, 2149211523, 270346401, 3357349936, 4028446585, 
          4028397243, 3223140735, 2015162232, 1880876222, 2552019813, 4162638467, 672989433, 4028423869, 2417838948, 1746749073, 
          2015166597, 404484460, 4028422077, 2015091905, 1478290469, 3357347112, 2552037501, 2015182006, 1209871950, 1746743277, 
          1075617925, 2417786403, 2552044042, 941440522, 538728613, 3357198107, 1880875372, 2149381766, 2015182866, 4162594049, 
          3760012016, 4028365269, 4162634389, 3088913529, 2417824218, 1612457852, 3223117087, 3894215445, 1478225261, 1075528298, 
          2417832869, 4028377514, 2686245397, 4162642960, 1344041891, 941407911, 2954701907, 1880959823, 1746748846, 2820473678, 
          3223069704, 1344059546, 1478310496, 1612485641, 1209870019, 1478309582, 404535455, 3625796676, 672983476, 1880955653, 
          2954702177, 941411125, 941421832, 3088921911, 807156468, 3357351969, 2820488104, 3357354564, 3088906951, 1870862, 3760012704...}
        src = 0x7ffff7ff4c72 ""
        dst = <optimized out>
        src_end = 0x7ffff7ff4c6e "\"\031`{"
        dst_end = 0x7ffff7dcdc6e "\"\031`{"
        pfind = <optimized out>
        pcur = <optimized out>
        cur_hash = <optimized out>
        p_last_lit = <optimized out>
        cpy_len = <optimized out>
        match_dist = <optimized out>
        flag = <optimized out>
        pflag = <optimized out>
        cache = <optimized out>
        cur_u32 = <optimized out>
---Type <return> to continue, or q <return> to quit--- 
#1  0x00000000005d9b51 in lzbench_shrinker_compress (inbuf=inbuf@entry=0x7ffff7e20010 "OggS", insize=insize@entry=1920106, 
    outbuf=outbuf@entry=0x7ffff7bf9010 <incomplete sequence \343>, outsize=outsize@entry=2256507) at _lzbench/compressors.cpp:1064
No locals.
#2  0x00000000005cbf72 in lzbench_compress (workmem=0x0, param2=0, param1=0, outsize=2256507, 
    outbuf=0x7ffff7bf9010 <incomplete sequence \343>, insize=1920106, inbuf=0x7ffff7e20010 "OggS", compr_lens=..., 
    compress=0x5d9b40 <lzbench_shrinker_compress(char*, unsigned long, char*, unsigned long, unsigned long, unsigned long, char*)>, 
    chunk_size=<optimized out>, params=0x7fffffffddc0) at _lzbench/lzbench.cpp:152
        clen = <optimized out>
        part = 1920106
        sum = 0
        start = 0x7ffff7e20010 "OggS"
#3  lzbench_test (params=params@entry=0x7fffffffddc0, desc=desc@entry=0xab5f78 <comp_desc+1848>, level=level@entry=0, 
    inbuf=inbuf@entry=0x7ffff7e20010 "OggS", insize=insize@entry=1920106, compbuf=compbuf@entry=0x7ffff7bf9010 <incomplete sequence \343>, 
    comprsize=2256507, decomp=0x7ffff7a20010 "", param1=0, ticksPerSecond=..., param2=0) at _lzbench/lzbench.cpp:239
        nanosec = 6974727
        ii = 1
        start_ticks = {tv_sec = 1238077, tv_nsec = 777780529}
        end_ticks = {tv_sec = 140737488346432, tv_nsec = 0}
        complen = 0
        ctime = {<std::_Vector_base<unsigned long, std::allocator<unsigned long> >> = {
            _M_impl = {<std::allocator<unsigned long>> = {<__gnu_cxx::new_allocator<unsigned long>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}
        dtime = {<std::_Vector_base<unsigned long, std::allocator<unsigned long> >> = {
            _M_impl = {<std::allocator<unsigned long>> = {<__gnu_cxx::new_allocator<unsigned long>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}
        compr_lens = {<std::_Vector_base<unsigned long, std::allocator<unsigned long> >> = {
            _M_impl = {<std::allocator<unsigned long>> = {<__gnu_cxx::new_allocator<unsigned long>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}}, <No data fields>}
        decomp_error = false
        workmem = <optimized out>
        blosclz = false
#4  0x00000000005ccca0 in lzbench_test_with_params (params=0x7fffffffddc0, namesWithParams=<optimized out>, inbuf=0x7ffff7e20010 "OggS", 
    insize=1920106, compbuf=0x7ffff7bf9010 <incomplete sequence \343>, comprsize=2256507, decomp=0x7ffff7a20010 "", ticksPerSecond=...)
    at _lzbench/lzbench.cpp:336
---Type <return> to continue, or q <return> to quit---
        level = 0
        i = <optimized out>
        found = true
        delimiters = "/"
        delimiters2 = ","
        copy = 0x5d6ba80 "shrinker"
        copy2 = 0x5d6ba60 "shrinker"
        token = <optimized out>
        token2 = <optimized out>
        token3 = <optimized out>
        save_ptr = 0x5d6ba88 ""
        save_ptr2 = 0x5d6ba68 ""
#5  0x00000000005cceac in lzbenchmark (params=0x7fffffffddc0, in=<optimized out>, encoder_list=0x5d6b810 "shrinker")
    at _lzbench/lzbench.cpp:389
        comprsize = <optimized out>
        insize = <optimized out>
        inbuf = 0x7ffff7e20010 "OggS"
        compbuf = 0x7ffff7bf9010 <incomplete sequence \343>
        decomp = 0x7ffff7a20010 ""
#6  0x00000000004013e4 in main (argc=<optimized out>, argv=0x7fffffffdf30) at _lzbench/lzbench.cpp:499
        in = 0x5d6b830
        params = {timetype = FASTEST, textformat = TEXT, c_iters = 1, d_iters = 3, chunk_size = 1920106, cspeed = 0, verbose = 0, 
          results = {<std::_Vector_base<string_table, std::allocator<string_table> >> = {
              _M_impl = {<std::allocator<string_table>> = {<__gnu_cxx::new_allocator<string_table>> = {<No data fields>}, <No data fields>}, _M_start = 0x5d6bb10, _M_finish = 0x5d6bb48, _M_end_of_storage = 0x5d6bb48}}, <No data fields>}}
        encoder_list = <optimized out>
        sort_col = <optimized out>
```

**Comment by inikep** [comment]
Thanks, changed to -O2
